spring.application.name=banco-xyz-batch
spring.batch.job.enabled=false

# Evita que el job se dispare automáticamente en cada arranque si más adelante quieres controlarlo por parámetros
spring.batch.jdbc.initialize-schema=always

# PostgreSQL (vía Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/bancoxyz
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=bancoxyz
spring.datasource.password=bancoxyz123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.batch.job.name=transaccionJob
#spring.batch.job.name=cuentaInteresJob
#spring.batch.job.name=cuentaAnualJob
