server:
  port: 8081

spring:
  application:
    name: bff-web

core:
  service-id: banco-xyz-core   # nombre lógico registrado en Eureka

resilience4j:
  circuitbreaker:
    instances:
      coreService:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    instances:
      coreService:
        timeout-duration: 3s
  retry:
    instances:
      coreService:
        max-attempts: 2
        wait-duration: 500ms
