server:
  port: 8081

spring:
  application:
    name: bff-web

# Nombres lógicos (Eureka) de los servicios que consume el canal Web
services:
  cuentas: cuentas-service
  clientes: clientes-service
  core: banco-xyz-core

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        ignore-exceptions:
          - java.util.NoSuchElementException
    instances:
      cuentasService:
        base-config: default
      clientesService:
        base-config: default
      coreService:
        base-config: default
  retry:
    configs:
      default:
        max-attempts: 2
        wait-duration: 500ms
        ignore-exceptions:
          - java.util.NoSuchElementException
    instances:
      cuentasService:
        base-config: default
      clientesService:
        base-config: default
      coreService:
        base-config: default
