server:
  port: 8085

spring:
  application:
    name: cuentas-service
  kafka:
    consumer:
      group-id: cuentas-service

clientes:
  service-id: clientes-service

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      clientesService:
        base-config: default
  retry:
    configs:
      default:
        max-attempts: 2
        wait-duration: 500ms
    instances:
      clientesService:
        base-config: default
