spring.application.name=bff-atm
spring.config.import=optional:configserver:http://localhost:8888

bff.atm.username=atm-client
bff.atm.password=atm-secret

logging.level.com.netflix.discovery=DEBUG
logging.level.com.netflix.eureka=DEBUG